apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyflaskapp-deployment
  labels:
    app: pyflaskapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pyflaskapp
  template:
    metadata:
      labels:
        app: pyflaskapp
    spec:
      containers:
      - name: pyflaskapp-container
        image: pouellette123/sba-pyflaskapp
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pyflaskapp-service
spec:
  type: NodePort
  selector:
    app: pyflaskapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32001
